name: Build/Release

on:
    release:
        types: [published]
    workflow_dispatch:
        inputs:
            tag:
                description: 'v1.0'
                required: true

permissions:
  contents: write

jobs:
    build-and-upload:
        runs-on: ubuntu-latest
        name: Build and Upload Assets

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js with Corepack (Yarn)
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'

            - name: Enable Corepack and install dependencies with Yarn
              run: |
                  corepack enable
                  YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install

            - name: Run build script
              run: node build.mjs

            # If triggered by a Release event, GitHub provides upload_url automatically.
            - name: Upload assets (release event)
              if: ${{ github.event_name == 'release' }}
              uses: softprops/action-gh-release@v2
              with:
                files: dist/**
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # If triggered manually, you must tell the action which tag to use.
            - name: Upload assets (manual tag)
              if: ${{ github.event_name == 'workflow_dispatch' }}
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ github.event.inputs.tag }}   # <-- not "inputs.tag"
                files: dist/**
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
